import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafe',
    position: 'relative',
  },
  content: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 60,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  
  titleSection: {
    alignItems: 'center',
    marginBottom: 60,
  },
  appTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#2c3e50',
    letterSpacing: 8,
    textShadowColor: 'rgba(74, 144, 226, 0.2)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
    marginBottom: 8,
  },
  appSubtitle: {
    fontSize: 16,
    fontWeight: '300',
    color: '#7f8c8d',
    letterSpacing: 2,
    textTransform: 'uppercase',
    opacity: 0.8,
  },
  
  // Partie du LOGO CLIQUABLE !
  logoTouchable: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  softGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#e8f4fd',
    shadowColor: '#4a90e2',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 25,
    elevation: 10,
  },
  backgroundCircle: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 15,
  },
  modernCross: {
    width: 130,
    height: 130,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 65,
    marginBottom: 0,
    elevation: 12,
    shadowColor: '#4a90e2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    borderWidth: 3,
    borderColor: '#e8f4fd',
    position: 'relative',
  },
  crossVertical: {
    position: 'absolute',
    width: 14,
    height: 55,
    backgroundColor: '#2ecc71',
    borderRadius: 7,
    shadowColor: '#2ecc71',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  crossHorizontal: {
    position: 'absolute',
    width: 55,
    height: 14,
    backgroundColor: '#2ecc71',
    borderRadius: 7,
    shadowColor: '#2ecc71',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  decorativeDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    backgroundColor: '#4a90e2',
    borderRadius: 2,
    opacity: 0.7,
  },
  elegantRing: {
    position: 'absolute',
    width: 170,
    height: 170,
    borderRadius: 85,
    borderWidth: 2,
    borderColor: '#d6ebf7',
    opacity: 0.8,
  },
  
  
  listeningIndicator: {
    position: 'absolute',
    top: -20,
    backgroundColor: '#ffffff',
    borderRadius: 15,
    paddingHorizontal: 8,
    paddingVertical: 4,
    shadowColor: '#e74c3c',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  listeningText: {
    fontSize: 16,
  },
  
  
  instructionsContainer: {
    alignItems: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
  },
  instructionTitle: {
    fontSize: 18,
    color: '#2c3e50',
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  instructionSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    lineHeight: 20,
  },
  listeningHint: {
    fontSize: 12,
    color: '#e74c3c',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  
  
  topMenu: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 10,
  },
  chatButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4a90e2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  chatButtonText: {
    fontSize: 20,
  },
  
  
  slideContainer: {
    width: width * 0.8,
    marginBottom: 40,
  },
  slideTrack: {
    height: 60,
    backgroundColor: '#e8f4fd',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    shadowColor: '#4a90e2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  slideText: {
    fontSize: 16,
    color: '#4a90e2',
    fontWeight: '500',
    letterSpacing: 1,
    textAlign: 'center',
  },
  progressIndicator: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: '100%',
    backgroundColor: 'rgba(74, 144, 226, 0.1)',
    borderRadius: 30,
  },
  slideThumb: {
    position: 'absolute',
    left: 5,
    width: 50,
    height: 50,
    backgroundColor: '#4a90e2',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4a90e2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  slideThumbIcon: {
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
  },
});
