services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sana-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
      - SALT=${SALT:-test_salt}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - TTS_URL=${TTS_URL:-https://api.elevenlabs.io/v1/text-to-speech/B4wUDSZmHFnxqY60nxXm}
    networks:
      - sana-network
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:

networks:
  sana-network:
    driver: bridge
