name: Version Check

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/version-check.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/version-check.yml'

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Nécessaire pour accéder à l'historique des tags

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging

    - name: Check version increment
      run: |
        cd backend
        python scripts/check_version.py
